// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OFOP.Core.Models
{
    public partial class Menu
    {
        public Menu()
        {
            Orders = new HashSet<Order>();
            Ratings = new HashSet<Rating>();
        }

        public int MenuId { get; set; }
        public string MenuName { get; set; }
        public int MenuTypeId { get; set; }
        public decimal Price { get; set; }
        public byte[] MenuImage { get; set; }
        public string Ingredients { get; set; }
        public bool MenuActive { get; set; }
        public DateTime MenuCreatedDate { get; set; }
        public int Cook { get; set; }

        public virtual User CookNavigation { get; set; }
        public virtual MenuType MenuType { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }
    }
}