// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OFOP.Core.Models
{
    public partial class UserType
    {
        public UserType()
        {
            Users = new HashSet<User>();
        }

        public int UtypeId { get; set; }
        public string UtName { get; set; }

        public virtual ICollection<User> Users { get; set; }
    }
}