// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OFOP.Core.Models
{
    public partial class User
    {
        public User()
        {
            Menus = new HashSet<Menu>();
            Orders = new HashSet<Order>();
            Ratings = new HashSet<Rating>();
        }

        public int CustId { get; set; }
        public string CustName { get; set; }
        public string CustUsername { get; set; }
        public string CustPassword { get; set; }
        public string CustTelNumber { get; set; }
        public string CustAddress { get; set; }
        public string CustPostCode { get; set; }
        public string CustEmail { get; set; }
        public int UserType { get; set; }
        public DateTime? CreatedDate { get; set; }

        public virtual UserType UserTypeNavigation { get; set; }
        public virtual ICollection<Menu> Menus { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }
    }
}